import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Navigation from "./Components/nav/Navigation";
import Providers from "@/redux/provider";
import OfferCarousel from "./Components/Carousel/Carousel";
import FooterPage from "./Components/Footer/FooterPage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My_Next_App",
  description: "Generated by Shaima",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container-fluid">
          <Navigation></Navigation>
          <OfferCarousel></OfferCarousel>

          <Providers> {children} </Providers>
          <FooterPage></FooterPage>
        </div>
      </body>
    </html>
  );
}
