import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Navigation from "./Components/nav/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My_Next_App",
  description: "Generated by Shaima",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="container-fluid">
          <Navigation></Navigation>
          {/* <h1 className="text-center">My Next_app</h1> */}
          {children}
          <p className="text-center   bg-primary m-0 p-0"> @_my_next_app..</p>
        </div>
      </body>


    </html>
  );
}
